/* Generated by Yosys 0.25+83 (git sha1 755b753e1, aarch64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "simple.sv:1.1-15.10" *)
module simple(clk, x, y, o, scan_in, scan_en, scan_out);
  wire _0_;
  (* src = "simple.sv:2.17-2.20" *)
  input clk;
  wire clk;
  (* src = "simple.sv:5.24-5.25" *)
  output [3:0] o;
  wire [3:0] o;
  input scan_en;
  wire scan_en;
  input scan_in;
  wire scan_in;
  output scan_out;
  reg scan_out;
  (* src = "simple.sv:8.17-8.22" *)
  reg \shreg[0] ;
  (* src = "simple.sv:8.17-8.22" *)
  reg \shreg[1] ;
  (* src = "simple.sv:8.17-8.22" *)
  reg \shreg[2] ;
  (* src = "simple.sv:8.17-8.22" *)
  wire \shreg[3] ;
  (* src = "simple.sv:3.17-3.18" *)
  input x;
  wire x;
  (* src = "simple.sv:4.23-4.24" *)
  input [3:0] y;
  wire [3:0] y;
  (* \always_ff  = 32'd1 *)
  (* src = "simple.sv:11.5-13.8" *)
  always @(posedge clk)
    \shreg[0]  <= _0_;
  (* \always_ff  = 32'd1 *)
  (* src = "simple.sv:11.5-13.8" *)
  always @(posedge clk)
    \shreg[1]  <= \shreg[0] ;
  (* \always_ff  = 32'd1 *)
  (* src = "simple.sv:11.5-13.8" *)
  always @(posedge clk)
    \shreg[2]  <= \shreg[1] ;
  (* \always_ff  = 32'd1 *)
  (* src = "simple.sv:11.5-13.8" *)
  always @(posedge clk)
    scan_out <= \shreg[2] ;
  assign o = { scan_out, \shreg[2] , \shreg[1] , \shreg[0]  } ^ (* src = "simple.sv:9.16-9.25" *) y;
  assign _0_ = scan_en ? scan_in : x;
  assign \shreg[3]  = scan_out;
endmodule
